
# PyZ3950_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftLOGOPATTRSET COMMA LOGOP LPAREN QUAL QUOTEDVALUE RELOP RPAREN SET SLASH WORDtop : cclfind_or_attrsetcclfind_or_attrset : cclfindcclfind_or_attrset : ATTRSET LPAREN WORD SLASH cclfind RPARENcclfind : cclfind LOGOP elementscclfind : elementselements : LPAREN cclfind RPARENelements : SET RELOP WORDelements : valelements : quallist RELOP valquallist : QUALquallist : quallist COMMA QUALval : QUOTEDVALUEval : val WORDval : WORD'
    
_lr_action_items = {'ATTRSET':([0,],[4,]),'LPAREN':([0,4,5,13,26,],[5,14,5,5,5,]),'SET':([0,5,13,26,],[8,8,8,8,]),'QUOTEDVALUE':([0,5,13,18,26,],[11,11,11,11,11,]),'WORD':([0,5,6,9,11,13,14,16,17,18,24,26,],[6,6,-14,17,-12,6,21,23,-13,6,17,6,]),'QUAL':([0,5,13,19,26,],[12,12,12,25,12,]),'$end':([1,2,3,6,7,9,11,17,20,22,23,24,28,],[0,-1,-2,-14,-5,-8,-12,-13,-4,-6,-7,-9,-3,]),'LOGOP':([3,6,7,9,11,15,17,20,22,23,24,27,],[13,-14,-5,-8,-12,13,-13,-4,-6,-7,-9,13,]),'RPAREN':([6,7,9,11,15,17,20,22,23,24,27,],[-14,-5,-8,-12,22,-13,-4,-6,-7,-9,28,]),'RELOP':([8,10,12,25,],[16,18,-10,-11,]),'COMMA':([10,12,25,],[19,-10,-11,]),'SLASH':([21,],[26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'top':([0,],[1,]),'cclfind_or_attrset':([0,],[2,]),'cclfind':([0,5,26,],[3,15,27,]),'elements':([0,5,13,26,],[7,7,20,7,]),'val':([0,5,13,18,26,],[9,9,9,24,9,]),'quallist':([0,5,13,26,],[10,10,10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> top","S'",1,None,None,None),
  ('top -> cclfind_or_attrset','top',1,'p_top','ccl.py',147),
  ('cclfind_or_attrset -> cclfind','cclfind_or_attrset',1,'p_cclfind_or_attrset_1','ccl.py',151),
  ('cclfind_or_attrset -> ATTRSET LPAREN WORD SLASH cclfind RPAREN','cclfind_or_attrset',6,'p_cclfind_or_attrset_2','ccl.py',155),
  ('cclfind -> cclfind LOGOP elements','cclfind',3,'p_ccl_find_1','ccl.py',159),
  ('cclfind -> elements','cclfind',1,'p_ccl_find_2','ccl.py',163),
  ('elements -> LPAREN cclfind RPAREN','elements',3,'p_elements_1','ccl.py',167),
  ('elements -> SET RELOP WORD','elements',3,'p_elements_2','ccl.py',189),
  ('elements -> val','elements',1,'p_elements_3','ccl.py',195),
  ('elements -> quallist RELOP val','elements',3,'p_elements_4','ccl.py',199),
  ('quallist -> QUAL','quallist',1,'p_quallist_1','ccl.py',206),
  ('quallist -> quallist COMMA QUAL','quallist',3,'p_quallist_2','ccl.py',210),
  ('val -> QUOTEDVALUE','val',1,'p_val_1','ccl.py',214),
  ('val -> val WORD','val',2,'p_val_2','ccl.py',218),
  ('val -> WORD','val',1,'p_val_3','ccl.py',222),
]
